version: "2"
services:
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - /tmp/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: lab4
      MYSQL_DATABASE: spi
  fe:
    build: "./web"
    ports:
      - 8080:8080
    depends_on:
     - db
    environment:
      ENV_VAR1: pepito

  storage:
    build: "./storageService"
    ports:
      - 8082:8082
    depends_on:
      - fe
    environment:
      ENV_VAR1: pepitin
  app:
    build: "./authServ"
    ports:
      - 8081:8081
    depends_on:
      - storage
    environment:
      ENV_VAR1: pepe
